<div class="todo-list">
   <form action="">
        <div class="add-field">
            <div class="input-field">
                <input type="text" class="text-input title-text" placeholder="Enter title here">
            </div>
            <button class="action primary add">Add</button>
        </div>

        <div class="list">
            <ul class="list-items-container" id="todoListContainer">
                <!-- JS will render tasks here -->
            </ul>
        </div>
   </form>
</div>

<script type="module" src="src/components/todolistcomponent/script.js"></script>
<script type="module" src="src/components/todolistcomponent/get-tasks.js"></script>
<script type="module" src="src/components/todolistcomponent/deleteTask.js"></script>
